import type { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'

import { cn } from '@/lib/utils'
import './globals.css'

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<Readonly<{ children: ReactNode }>> = ({
  children
}) => {
  return (
    <html lang="en">
      <body className={cn(inter.className, poppins.variable)}>{children}</body>
    </html>
  );
}

export default RootLayout